export const COMPASS_GRID_SIZE = 6;

export const COMPASS_CARD_PADDING = 18;

export const COMPASS_OUTER_RADIUS = 0;

export const COMPASS_SELECTION_INSET = 3;

export const COMPASS_MAX_SELECTED_CELLS = 10;

export const COMPASS_MAX_SUGGESTED_EMOTIONS = 20;